name: Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: terraform-linters/setup-tflint@v4
      - name: tflint
        run: |
          tflint --init
          tflint \
            --format compact \
            --recursive \
            --minimum-failure-severity=warning \
            --config "$(pwd)/.tflint.hcl"
